import { Disc } from "../App";

export const found_discs: Disc[] = [
  {
    id: 1,
    course: "Tranquility Trails",
    name: "C. Deck",
    disc: "Raptor",
    phoneNumber: "4266",
    bin: "1",
    dateFound: "2023-10-02",
    dateTexted: "2023-10-16",
    dateClaimed: "2023-10-04",
    status: "Claimed",
    comments: "Green.",
    color: "Green",
    pickupDeadline: "2023-12-01",
    brand: "MVP",
  },
  {
    id: 2,
    course: "501 Disc Golf",
    name: "Zack",
    disc: "Instinct",
    phoneNumber: "3807",
    bin: "1",
    dateFound: "2023-09-29",
    dateTexted: "2023-10-17",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Neo Plastic",
    color: "Gold",
    pickupDeadline: "2023-11-28",
    brand: "Innova",
  },
  {
    id: 3,
    course: "Girdwood Forest Fair Park",
    name: "Noah",
    disc: "Anax",
    phoneNumber: "5253",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "ESP",
    color: "Blue",
    pickupDeadline: "2023-12-02",
    brand: "Lonestar",
  },
  {
    id: 4,
    course: "The Beast",
    name: "E. Hopper",
    disc: "King",
    phoneNumber: "4066",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-12-02",
    brand: "Lonestar",
  },
  {
    id: 5,
    course: "Windy Ridge Disc Golf at Mitchusson Park",
    name: "KS",
    disc: "Escape",
    phoneNumber: "3170",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Burst",
    color: "Blue",
    pickupDeadline: "2023-12-02",
    brand: "Discmania",
  },
  {
    id: 6,
    course: "DeLaveaga",
    name: "C. K",
    disc: "Panther",
    phoneNumber: "1050",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-05",
    status: "Claimed",
    comments: "Champion",
    color: "Pink",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 7,
    course: "DeLaveaga",
    name: "R. K",
    disc: "Buzzz",
    phoneNumber: "9441",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-03",
    status: "Claimed",
    comments: "Light blue big z",
    color: "",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 8,
    course: "Girdwood Forest Fair Park",
    name: "B. Chin",
    disc: "Meta essence",
    phoneNumber: "1579",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 9,
    course: "Tranquility Trails",
    name: "Red",
    disc: "Explorer",
    phoneNumber: "6566",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 10,
    course: "Maple Hill",
    name: "A. Aamsson",
    disc: "Teebird",
    phoneNumber: "0750",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 11,
    course: "Tranquility Trails",
    name: "NTM",
    disc: "Resistor",
    phoneNumber: "1712",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Neutron",
    color: "White",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 12,
    course: "Fox Run Meadows",
    name: "E. K",
    disc: "Leopard",
    phoneNumber: "3170",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 13,
    course: "Maple Hill",
    name: "Enzo",
    disc: "King",
    phoneNumber: "4933",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Burst",
    color: "Orange",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 14,
    course: "Tranquility Trails",
    name: "Tyler",
    disc: "Trace",
    phoneNumber: "2734",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-05",
    status: "Claimed",
    comments: "Plasma",
    color: "Red",
    pickupDeadline: "2023-12-02",
    brand: "MVP",
  },
  {
    id: 15,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "Shawn",
    disc: "Inertia",
    phoneNumber: "3864",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Plasma",
    color: "Orange",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 16,
    course: "Fox Run Meadows",
    name: "B. Farley",
    disc: "Firebird",
    phoneNumber: "3242",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 17,
    course: "Tranquility Trails",
    name: "R. Sipia",
    disc: "Orbital",
    phoneNumber: "3547",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Neutron",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 18,
    course: "10-3 at CB",
    name: "B. Vail",
    disc: "Monarch",
    phoneNumber: "9707",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 19,
    course: "Tranquility Trails",
    name: "K. B",
    disc: "Underworld",
    phoneNumber: "3761",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Burst",
    color: "Purple/Blue",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 20,
    course: "Girdwood Forest Fair Park",
    name: "J. H",
    disc: "Genius",
    phoneNumber: "8629",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "White",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 21,
    course: "Tranquility Trails",
    name: "H. S.",
    disc: "Diamond",
    phoneNumber: "8059",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-17",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "Lonestar",
  },
  {
    id: 22,
    course: "Rollin Ridge",
    name: "Brown",
    disc: "Pure",
    phoneNumber: "3823",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 23,
    course: "Tranquility Trails",
    name: "A. Redcay",
    disc: "Giant",
    phoneNumber: "0099",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "2023-10-13",
    status: "Claimed",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 24,
    course: "Idlewild",
    name: "Eric",
    disc: "Athena",
    phoneNumber: "2739",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-05",
    status: "Claimed",
    comments: '"1st ace" on back',
    color: "Blue",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 25,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "H",
    disc: "Anax",
    phoneNumber: "0675",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Esp",
    color: "Purple/Pink",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 26,
    course: "DeLaveaga",
    name: "B. the baker",
    disc: "F2",
    phoneNumber: "7712",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 27,
    course: "1000 Acres Ranch Disc Golf Course",
    name: "RP",
    disc: "Buzzz",
    phoneNumber: "",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-17",
    status: "Claimed",
    comments: "Cosmic stamp",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "MVP",
  },
  {
    id: 28,
    course: "Tranquility Trails",
    name: "J. Conley",
    disc: "Trace",
    phoneNumber: "2734",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "",
    dateClaimed: "2023-10-05",
    status: "Claimed",
    comments: "Plasma",
    color: "",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 29,
    course: "Tranquility Trails",
    name: "AR",
    disc: "Avenger ss",
    phoneNumber: "0209",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Sedgley woods stamp",
    color: "Red",
    pickupDeadline: "2023-12-02",
    brand: "MVP",
  },
  {
    id: 30,
    course: "DeLaveaga",
    name: "Schweider",
    disc: "Eagle",
    phoneNumber: "4624",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-02",
    brand: "MVP",
  },
  {
    id: 31,
    course: "Tranquility Trails",
    name: "N. Ott",
    disc: "Shryke",
    phoneNumber: "6044",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-12-02",
    brand: "Birdie",
  },
  {
    id: 32,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "ZH",
    disc: "Maya",
    phoneNumber: "5518",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Red",
    pickupDeadline: "2023-12-02",
    brand: "Discraft",
  },
  {
    id: 33,
    course: "65th Infantry Veterans Disc Golf Course",
    name: "Harker",
    disc: "Valkyrie",
    phoneNumber: "8487",
    bin: "1",
    dateFound: "2023-10-03",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Light blue",
    pickupDeadline: "2023-12-02",
    brand: "Innova",
  },
  {
    id: 34,
    course: "50 Acre Park",
    name: "Andrew",
    disc: "DD Captain",
    phoneNumber: "8609",
    bin: "6",
    dateFound: "2023-07-31",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "",
    pickupDeadline: "2023-09-29",
    brand: "MVP",
  },
  {
    id: 35,
    course: "Girdwood Forest Fair Park",
    name: "S. Danner",
    disc: "Star Aviar",
    phoneNumber: "1323",
    bin: "6",
    dateFound: "2023-07-31",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-09-29",
    brand: "Innova",
  },
  {
    id: 36,
    course: "50 Acre Park",
    name: "Andy",
    disc: "Genius",
    phoneNumber: "3807",
    bin: "6",
    dateFound: "2023-07-31",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-09-29",
    brand: "MVP",
  },
  {
    id: 37,
    course: "Windy Ridge Disc Golf at Mitchusson Park",
    name: "M. Orendorff",
    disc: "Meteor",
    phoneNumber: "0321",
    bin: "6",
    dateFound: "2023-07-31",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-09-29",
    brand: "MVP",
  },
  {
    id: 38,
    course: "Stafford Woods",
    name: "T. Schaffner",
    disc: "Star Beast",
    phoneNumber: "4927",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-11-05",
    brand: "Discraft",
  },
  {
    id: 39,
    course: "Fox Run Meadows",
    name: "P. r",
    disc: "Legacy Grinder",
    phoneNumber: "0733",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "white",
    pickupDeadline: "2023-11-05",
    brand: "MVP",
  },
  {
    id: 40,
    course: "A. J. Jolly Park",
    name: "AGG",
    disc: "Infinite pharaoh",
    phoneNumber: "0402",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 41,
    course: "Inverness Disc Golf Park",
    name: "T. C",
    disc: "Leopard 3",
    phoneNumber: "4915",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "Birdie",
  },
  {
    id: 42,
    course: "Idlewild",
    name: "J. Stoltzfus",
    disc: "Avenger SS",
    phoneNumber: "7968",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Esp",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "Discraft",
  },
  {
    id: 43,
    course: "Inverness Disc Golf Park",
    name: "M. D",
    disc: "Passion",
    phoneNumber: "4815",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-11-05",
    brand: "Birdie",
  },
  {
    id: 44,
    course: "10-3 at CB",
    name: "Nick",
    disc: "Genius",
    phoneNumber: "4469",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "White",
    pickupDeadline: "2023-11-05",
    brand: "Discmania",
  },
  {
    id: 45,
    course: "Inverness Disc Golf Park",
    name: "Nick",
    disc: "Shark",
    phoneNumber: "7813",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 46,
    course: "Rollin Ridge",
    name: "S. C",
    disc: "Zeus",
    phoneNumber: "7197",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-11-05",
    brand: "MVP",
  },
  {
    id: 47,
    course: "North Landing",
    name: "Craig",
    disc: "Champ Firebird",
    phoneNumber: "5410",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Tie Dye",
    pickupDeadline: "2023-11-05",
    brand: "Discraft",
  },
  {
    id: 48,
    course: "Hornets Nest",
    name: "L. Kozinski",
    disc: "Thunderstorms",
    phoneNumber: "9035",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 49,
    course: "Stafford Woods",
    name: "J. Deal",
    disc: "Champ Destroyer",
    phoneNumber: "0496",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-11-05",
    brand: "Birdie",
  },
  {
    id: 50,
    course: "Girdwood Forest Fair Park",
    name: "Petter",
    disc: "Glow TL",
    phoneNumber: "0496",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Glow",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 51,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "Michelangelo",
    disc: "Fission Hex",
    phoneNumber: "1544",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Red",
    pickupDeadline: "2023-11-05",
    brand: "Discmania",
  },
  {
    id: 52,
    course: "North Landing",
    name: "Cosenza",
    disc: "Valkyrie",
    phoneNumber: "4120",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 53,
    course: "DeLaveaga",
    name: "S. F",
    disc: "Destroyer",
    phoneNumber: "4326",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-05",
    brand: "MVP",
  },
  {
    id: 54,
    course: "A. J. Jolly Park",
    name: "Brent",
    disc: "Fission Photon",
    phoneNumber: "2266",
    bin: "3",
    dateFound: "2023-09-06",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Grey",
    pickupDeadline: "2023-11-05",
    brand: "Innova",
  },
  {
    id: 55,
    course: "Fountain Hills",
    name: "Megan",
    disc: "Wraith",
    phoneNumber: "0043",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "2023-10-13",
    status: "Claimed",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-10-19",
    brand: "Birdie",
  },
  {
    id: 56,
    course: "DeLaveaga",
    name: "Patrick",
    disc: "Champ Teebird",
    phoneNumber: "9035",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-10-19",
    brand: "MVP",
  },
  {
    id: 57,
    course: "50 Acre Park",
    name: "N. Repice",
    disc: "Barela Teebird",
    phoneNumber: "5559",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue Glow",
    pickupDeadline: "2023-10-19",
    brand: "MVP",
  },
  {
    id: 58,
    course: "501 Disc Golf",
    name: "Hamburgee",
    disc: "Orbital",
    phoneNumber: "7539",
    bin: "4",
    dateFound: "2023-08-22",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-10-21",
    brand: "Discmania",
  },
  {
    id: 59,
    course: "Bellevue State Park",
    name: "Jeff",
    disc: "Valkyrie",
    phoneNumber: "4206",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Red",
    pickupDeadline: "2023-10-19",
    brand: "MVP",
  },
  {
    id: 60,
    course: "Stafford Woods",
    name: "J. Rohnson",
    disc: "Sexton Firebird",
    phoneNumber: "3488",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue Glow",
    pickupDeadline: "2023-10-19",
    brand: "Discraft",
  },
  {
    id: 61,
    course: "The Beast",
    name: "J. Miller",
    disc: "Jawbreaker Raptor",
    phoneNumber: "8629",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "White",
    pickupDeadline: "2023-10-19",
    brand: "Innova",
  },
  {
    id: 62,
    course: "3 Creeks",
    name: "Rossi",
    disc: "Virus",
    phoneNumber: "",
    bin: "4",
    dateFound: "2023-08-22",
    dateTexted: "",
    dateClaimed: "2023-10-17",
    status: "Claimed",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-10-21",
    brand: "Innova",
  },
  {
    id: 63,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "J. R",
    disc: "Dx Archangel",
    phoneNumber: "2327",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-10-19",
    brand: "Discmania",
  },
  {
    id: 64,
    course: "Fountain Hills",
    name: "Torres",
    disc: "Star TL3",
    phoneNumber: "1505",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-10-19",
    brand: "Discraft",
  },
  {
    id: 65,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "Tyler",
    disc: "Crave",
    phoneNumber: "4213",
    bin: "4",
    dateFound: "2023-08-20",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-10-19",
    brand: "Discmania",
  },
  {
    id: 66,
    course: "Tranquility Trails",
    name: "Alex",
    disc: "Volt",
    phoneNumber: "3672",
    bin: "4",
    dateFound: "2023-08-22",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-10-21",
    brand: "MVP",
  },
  {
    id: 67,
    course: "Fountain Hills",
    name: "A. K",
    disc: "Disctroyer A medium",
    phoneNumber: "6628",
    bin: "5",
    dateFound: "2023-08-18",
    dateTexted: "2023-10-07",
    dateClaimed: "2023-10-10",
    status: "Claimed",
    comments: "",
    color: "White",
    pickupDeadline: "2023-10-17",
    brand: "Innova",
  },
  {
    id: 68,
    course: "Tranquility Trails",
    name: "M. M",
    disc: "Infinite Sphinx",
    phoneNumber: "6286",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "2023-10-09",
    status: "Claimed",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-10-12",
    brand: "Lonestar",
  },
  {
    id: 69,
    course: "Fountain Hills",
    name: "Chance",
    disc: "Champ Firebird",
    phoneNumber: "0286",
    bin: "5",
    dateFound: "2023-08-28",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments:
      "Real date found is 8/13/2023 but moving it so we donâ€™t add it to the $5 bin.",
    color: "Yellow",
    pickupDeadline: "2023-10-27",
    brand: "Lonestar",
  },
  {
    id: 70,
    course: "1000 Acres Ranch Disc Golf Course",
    name: "JK",
    disc: "Z Zone",
    phoneNumber: "8048",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Red",
    pickupDeadline: "2023-10-12",
    brand: "Discmania",
  },
  {
    id: 71,
    course: "Bellevue State Park",
    name: "Wiseman",
    disc: "Method",
    phoneNumber: "6930",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-10-12",
    brand: "Discmania",
  },
  {
    id: 72,
    course: "The Beast",
    name: "Konopka",
    disc: "Pro Leopard",
    phoneNumber: "0323",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-10-12",
    brand: "MVP",
  },
  {
    id: 73,
    course: "Blue Ribbon Pines",
    name: "Jay",
    disc: "Wraith",
    phoneNumber: "0296",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-10-12",
    brand: "Birdie",
  },
  {
    id: 74,
    course: "10-3 at CB",
    name: "J. Miller",
    disc: "Raptor",
    phoneNumber: "0200",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-10-12",
    brand: "Innova",
  },
  {
    id: 75,
    course: "DeLaveaga",
    name: "P. Martin",
    disc: "Roadrunner",
    phoneNumber: "2250",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-10-12",
    brand: "MVP",
  },
  {
    id: 76,
    course: "10-3 at CB",
    name: "Chance",
    disc: "Lucid",
    phoneNumber: "6792",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue Clear",
    pickupDeadline: "2023-10-12",
    brand: "Dynamic Discs",
  },
  {
    id: 77,
    course: "The Beast",
    name: "ACO",
    disc: "Aviar",
    phoneNumber: "0439",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "White",
    pickupDeadline: "2023-10-12",
    brand: "MVP",
  },
  {
    id: 78,
    course: "Flip City",
    name: "N. P",
    disc: "Escape",
    phoneNumber: "6996",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "x-out",
    color: "Blue",
    pickupDeadline: "2023-10-12",
    brand: "Dynamic Discs",
  },
  {
    id: 79,
    course: "North Landing",
    name: "Jake",
    disc: "Roc 3",
    phoneNumber: "3672",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-10-12",
    brand: "Discmania",
  },
  {
    id: 80,
    course: "3 Creeks",
    name: "Matt",
    disc: "Katana",
    phoneNumber: "1409",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-10-12",
    brand: "Discmania",
  },
  {
    id: 81,
    course: "2022 Lucky Disc Golf Open Freeman North",
    name: "C. Boucher",
    disc: "Heat",
    phoneNumber: "0260",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-10-12",
    brand: "MVP",
  },
  {
    id: 82,
    course: "50 Acre Park",
    name: "A. Parungao",
    disc: "Truth",
    phoneNumber: "9454",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "White",
    pickupDeadline: "2023-10-12",
    brand: "Dynamic Discs",
  },
  {
    id: 83,
    course: "Blue Ribbon Pines",
    name: "C. Kamingkas",
    disc: "Wave",
    phoneNumber: "3719",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-10-12",
    brand: "MVP",
  },
  {
    id: 84,
    course: "Bellevue State Park",
    name: "Dan",
    disc: "Escape",
    phoneNumber: "8085",
    bin: "5",
    dateFound: "2023-08-13",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "For Sale in $5 Bin",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-10-12",
    brand: "Dynamic Discs",
  },
  {
    id: 85,
    course: "65th Infantry Veterans Disc Golf Course",
    name: "B. Wellner",
    disc: "Judge",
    phoneNumber: "8208",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-18",
    brand: "Dynamic Discs",
  },
  {
    id: 86,
    course: "10-3 at CB",
    name: "H. Snyder",
    disc: "Photon",
    phoneNumber: "9153",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "2023-10-09",
    status: "Claimed",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-18",
    brand: "Discmania",
  },
  {
    id: 87,
    course: "Maple Hill",
    name: "Meanberg",
    disc: "Truth",
    phoneNumber: "8953",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-11-18",
    brand: "Discmania",
  },
  {
    id: 88,
    course: "Bellevue State Park",
    name: "J. Doe",
    disc: "Wraith",
    phoneNumber: "4567",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-11-18",
    brand: "Innova",
  },
  {
    id: 89,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "R. W",
    disc: "PD",
    phoneNumber: "2114",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-11-18",
    brand: "MVP",
  },
  {
    id: 90,
    course: "Windy Ridge Disc Golf at Mitchusson Park",
    name: "J. S",
    disc: "Boss",
    phoneNumber: "5843",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Orange",
    pickupDeadline: "2023-11-18",
    brand: "Discmania",
  },
  {
    id: 91,
    course: "3 Creeks",
    name: "B. P",
    disc: "Charger",
    phoneNumber: "2739",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "",
    dateClaimed: "2023-10-05",
    status: "Claimed",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-11-18",
    brand: "Birdie",
  },
  {
    id: 92,
    course: "The Beast",
    name: "Laren",
    disc: "Destroyer",
    phoneNumber: "5189",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-11-18",
    brand: "MVP",
  },
  {
    id: 93,
    course: "Fountain Hills",
    name: "Acosta",
    disc: "Luna",
    phoneNumber: "0535",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-11-18",
    brand: "Discraft",
  },
  {
    id: 94,
    course: "Girdwood Forest Fair Park",
    name: "Testing",
    disc: "Luna",
    phoneNumber: "0535",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-11-18",
    brand: "Birdie",
  },
  {
    id: 95,
    course: "Fox Run Meadows",
    name: "J. C",
    disc: "Bottom stamp Destroyer",
    phoneNumber: "6086",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "White",
    pickupDeadline: "2023-11-18",
    brand: "Discmania",
  },
  {
    id: 96,
    course: "Bellevue State Park",
    name: "Testing 3",
    disc: "Roc3",
    phoneNumber: "3455",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "9/19 green",
    color: "Green",
    pickupDeadline: "2023-11-18",
    brand: "Discraft",
  },
  {
    id: 97,
    course: "Flip City",
    name: "C. Deck",
    disc: "Volt",
    phoneNumber: "9429",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-18",
    brand: "MVP",
  },
  {
    id: 98,
    course: "Flip City",
    name: "M. S",
    disc: "Lariat",
    phoneNumber: "9148",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-11-18",
    brand: "Discraft",
  },
  {
    id: 99,
    course: "65th Infantry Veterans Disc Golf Course",
    name: "N. S",
    disc: "Envy",
    phoneNumber: "3268",
    bin: "2",
    dateFound: "2023-09-19",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Blue",
    pickupDeadline: "2023-11-18",
    brand: "Innova",
  },
  {
    id: 100,
    course: "501 Disc Golf",
    name: "M. Cowden",
    disc: "Test Disc",
    phoneNumber: "5555",
    bin: "22",
    dateFound: "2023-10-04",
    dateTexted: "",
    dateClaimed: "2023-10-04",
    status: "Claimed",
    comments: "this is a test",
    color: "Blue",
    pickupDeadline: "2023-12-03",
    brand: "MVP",
  },
  {
    id: 101,
    course: "2022 Lucky Disc Golf Open Freeman North",
    name: "Jerrald",
    disc: "G star Wraith",
    phoneNumber: "5487",
    bin: "1",
    dateFound: "2023-10-04",
    dateTexted: "2023-10-07",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-12-03",
    brand: "Birdie",
  },
  {
    id: 102,
    course: "50 Acre Park",
    name: "Jon",
    disc: "testing pickup deadline",
    phoneNumber: "5554",
    bin: "222",
    dateFound: "2023-10-06",
    dateTexted: "",
    dateClaimed: "2023-10-06",
    status: "Claimed",
    comments: "comments",
    color: "",
    pickupDeadline: "2023-12-05",
    brand: "Lonestar",
  },
  {
    id: 103,
    course: "3 Creeks",
    name: "Jon",
    disc: "Raptor",
    phoneNumber: "4266",
    bin: "12",
    dateFound: "2023-10-07",
    dateTexted: "2023-10-09",
    dateClaimed: "2023-10-09",
    status: "Claimed",
    comments: "This is a test",
    color: "Green",
    pickupDeadline: "2023-12-06",
    brand: "Discmania",
  },
  {
    id: 104,
    course: "Idlewild",
    name: "Timur",
    disc: "Volt",
    phoneNumber: "7731",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Gold",
    pickupDeadline: "2023-12-08",
    brand: "Lonestar",
  },
  {
    id: 105,
    course: "The Beast",
    name: "testingextraspace",
    disc: "Essence",
    phoneNumber: "2978",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-08",
    brand: "MVP",
  },
  {
    id: 106,
    course: "Maple Hill",
    name: "K. F",
    disc: "Buzzz",
    phoneNumber: "9072",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "2023-10-10",
    status: "Claimed",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-12-08",
    brand: "Birdie",
  },
  {
    id: 107,
    course: "Hornets Nest",
    name: "Joe",
    disc: "F7",
    phoneNumber: "5487",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Gold",
    pickupDeadline: "2023-12-08",
    brand: "MVP",
  },
  {
    id: 108,
    course: "Idlewild",
    name: "D. Jones",
    disc: "Helios",
    phoneNumber: "6784",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Yellow",
    pickupDeadline: "2023-12-08",
    brand: "Innova",
  },
  {
    id: 109,
    course: "S.Y. Wilson Arlington Sports Complex",
    name: "SandahlT",
    disc: "Pestilence",
    phoneNumber: "7302",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Gold",
    pickupDeadline: "2023-12-08",
    brand: "Innova",
  },
  {
    id: 110,
    course: "Hornets Nest",
    name: "Kyle",
    disc: "Pharoah",
    phoneNumber: "7302",
    bin: "6",
    dateFound: "2023-10-09",
    dateTexted: "2023-10-10",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-12-08",
    brand: "Birdie",
  },
  {
    id: 111,
    course: "Girdwood Forest Fair Park",
    name: "Turpin",
    disc: "Zeus",
    phoneNumber: "8139",
    bin: "1",
    dateFound: "2023-10-10",
    dateTexted: "2023-10-11",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Big Z plastic",
    color: "Yellow",
    pickupDeadline: "2023-12-09",
    brand: "Innova",
  },
  {
    id: 112,
    course: "50 Acre Park",
    name: "Torres",
    disc: "test",
    phoneNumber: "5555",
    bin: "999",
    dateFound: "2023-10-12",
    dateTexted: "",
    dateClaimed: "2023-10-12",
    status: "Claimed",
    comments: "testing",
    color: "",
    pickupDeadline: "2023-12-11",
    brand: "Lonestar",
  },
  {
    id: 113,
    course: "50 Acre Park",
    name: "I. buckinghwm",
    disc: "Leopard",
    phoneNumber: "4983",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-13",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "Dx plastic",
    color: "Gold",
    pickupDeadline: "2023-12-12",
    brand: "Innova",
  },
  {
    id: 114,
    course: "Rollin Ridge",
    name: "Russ",
    disc: "Warden",
    phoneNumber: "1673",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-13",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "White",
    pickupDeadline: "2023-12-12",
    brand: "Discraft",
  },
  {
    id: 115,
    course: "North Landing",
    name: "T. cooper",
    disc: "Hawkeye",
    phoneNumber: "5851",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-13",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Pink",
    pickupDeadline: "2023-12-12",
    brand: "Discmania",
  },
  {
    id: 116,
    course: "10-3 at CB",
    name: "Keith",
    disc: "Volt",
    phoneNumber: "2666",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-13",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Gold",
    pickupDeadline: "2023-12-12",
    brand: "MVP",
  },
  {
    id: 117,
    course: "3 Creeks",
    name: "Turpin",
    disc: "Undertaker",
    phoneNumber: "7654",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-14",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-12-12",
    brand: "Lonestar",
  },
  {
    id: 118,
    course: "Fountain Hills",
    name: "Timur",
    disc: "Crave",
    phoneNumber: "7473",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-14",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-12-12",
    brand: "Discraft",
  },
  {
    id: 119,
    course: "501 Disc Golf",
    name: "Rich",
    disc: "Falcor",
    phoneNumber: "8598",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-14",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Green",
    pickupDeadline: "2023-12-12",
    brand: "Lonestar",
  },
  {
    id: 120,
    course: "Flip City",
    name: "Jared",
    disc: "Trespass",
    phoneNumber: "0286",
    bin: "6",
    dateFound: "2023-10-13",
    dateTexted: "2023-10-14",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Teal blue",
    pickupDeadline: "2023-12-12",
    brand: "MVP",
  },
  {
    id: 121,
    course: "The Beast",
    name: "Ryan",
    disc: "Bottom stamp Destroyer",
    phoneNumber: "2739",
    bin: "6",
    dateFound: "2023-10-17",
    dateTexted: "2023-10-17",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "White",
    pickupDeadline: "2023-12-16",
    brand: "Birdie",
  },
  {
    id: 122,
    course: "Idlewild",
    name: "Scott",
    disc: "Volt",
    phoneNumber: "7503",
    bin: "6",
    dateFound: "2023-10-17",
    dateTexted: "2023-10-17",
    dateClaimed: "",
    status: "Text Sent, Waiting for Pickup",
    comments: "",
    color: "Purple",
    pickupDeadline: "2023-12-16",
    brand: "Innova",
  },
];
